import {
  Patient,
  Ambulance,
  Hospital,
  BloodInventory,
  Medicine,
  Allocation,
  Alert,
  LedgerBlock,
  FundTransfer,
  SimulationEvent,
} from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P-7F3A',
    triageSeverity: 'Critical',
    status: 'In Transit',
    injury: 'Tier 1 Polytrauma & Craniocerebral Injury',
    location: 'Sector 4, Kurla Industrial Junction',
    coordinates: [19.0728, 72.8826],
    vitals: { spo2: 88, bp: '85/55', pulse: 128, gcs: 8, respirationRate: 28 },
    assignedAmbulanceId: 'AMB-04',
    assignedHospitalId: 'HOSP-02',
    registeredTime: '14:28:10',
    etaMinutes: 8,
    notes: 'Invasive mechanical ventilation underway by paramedic team.',
  },
  {
    id: 'P-81D2',
    triageSeverity: 'Critical',
    status: 'Waiting',
    injury: 'Hypovolemic Shock & Pelvic Fracture',
    location: 'Bandra-Kurla Complex Arterial Cutoff',
    coordinates: [19.0657, 72.8687],
    vitals: { spo2: 89, bp: '80/50', pulse: 134, gcs: 9, respirationRate: 32 },
    registeredTime: '14:29:45',
    etaMinutes: 11,
    notes: 'Urgent blood transfusion match O- required.',
  },
  {
    id: 'P-91AC',
    triageSeverity: 'Critical',
    status: 'In Transit',
    injury: 'Acute Crush Syndrome & Chest Trauma',
    location: 'Sion Railway Footbridge Collapse',
    coordinates: [19.0416, 72.8624],
    vitals: { spo2: 91, bp: '92/60', pulse: 118, gcs: 10, respirationRate: 24 },
    assignedAmbulanceId: 'AMB-12',
    assignedHospitalId: 'HOSP-01',
    registeredTime: '14:22:15',
    etaMinutes: 4,
    notes: 'Bilateral chest decompression performed on scene.',
  },
  {
    id: 'P-209A',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Compound Tibia Fracture with Vascular Compromise',
    location: 'Santacruz East Highway Staging',
    coordinates: [19.0843, 72.8465],
    vitals: { spo2: 95, bp: '115/78', pulse: 98, gcs: 14, respirationRate: 20 },
    registeredTime: '14:15:30',
    etaMinutes: 15,
  },
  {
    id: 'P-334F',
    triageSeverity: 'Urgent',
    status: 'Allocated',
    injury: 'Secondary Blast Concussion & Severe Hemorrhage',
    location: 'Dharavi Depot 9 Transit Area',
    coordinates: [19.0434, 72.8567],
    vitals: { spo2: 94, bp: '105/70', pulse: 104, gcs: 13, respirationRate: 22 },
    assignedAmbulanceId: 'AMB-08',
    assignedHospitalId: 'HOSP-04',
    registeredTime: '14:18:02',
    etaMinutes: 12,
  },
  {
    id: 'P-502B',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Moderate Inhalation Injury & Superficial Burns',
    location: 'M-East Ward Relief Camp',
    coordinates: [19.0558, 72.9094],
    vitals: { spo2: 97, bp: '124/82', pulse: 84, gcs: 15, respirationRate: 18 },
    registeredTime: '14:02:11',
    notes: 'Walk-in casualty at field triage sector 2.',
  },
  {
    id: 'P-611D',
    triageSeverity: 'Critical',
    status: 'Waiting',
    injury: 'Traumatic Brain Injury & Subdural Hematoma',
    location: 'Chunabhatti Highway Bypass',
    coordinates: [19.0522, 72.8711],
    vitals: { spo2: 86, bp: '78/48', pulse: 142, gcs: 6, respirationRate: 34 },
    registeredTime: '14:31:00',
    notes: 'Immediate neurosurgical bay required.',
  },
  {
    id: 'P-118E',
    triageSeverity: 'Urgent',
    status: 'In Transit',
    injury: 'Abdominal Penetrating Trauma',
    location: 'Tilak Nagar Sector 3',
    coordinates: [19.0681, 72.8988],
    vitals: { spo2: 93, bp: '100/65', pulse: 110, gcs: 12, respirationRate: 22 },
    assignedAmbulanceId: 'AMB-15',
    assignedHospitalId: 'HOSP-03',
    registeredTime: '14:10:44',
    etaMinutes: 7,
  },
  {
    id: 'P-447K',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Closed Radius/Ulna Fracture',
    location: 'Chembur Naka Relief Camp',
    coordinates: [19.0596, 72.9002],
    vitals: { spo2: 98, bp: '122/80', pulse: 76, gcs: 15, respirationRate: 16 },
    registeredTime: '13:55:00',
  },
  {
    id: 'P-992Z',
    triageSeverity: 'Expectant',
    status: 'Waiting',
    injury: 'Non-salvageable Massive Trauma with Cardiac Arrest',
    location: 'Kurla Collapse Core Ground Zero',
    coordinates: [19.0712, 72.8798],
    vitals: { spo2: 0, bp: '0/0', pulse: 0, gcs: 3, respirationRate: 0 },
    registeredTime: '14:12:18',
    notes: 'Palliative comfort care protocol enacted.',
  },
  {
    id: 'P-404C',
    triageSeverity: 'Critical',
    status: 'Allocated',
    injury: 'Severe Flail Chest & Tension Pneumothorax',
    location: 'Ghatkopar East Flyover Ramp',
    coordinates: [19.0856, 72.9082],
    vitals: { spo2: 85, bp: '82/52', pulse: 130, gcs: 9, respirationRate: 30 },
    assignedAmbulanceId: 'AMB-02',
    assignedHospitalId: 'HOSP-02',
    registeredTime: '14:26:05',
    etaMinutes: 9,
  },
  {
    id: 'P-519A',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Second-degree Burns (35% TBSA)',
    location: 'Sakinaka Metro Station Perimeter',
    coordinates: [19.1025, 72.8871],
    vitals: { spo2: 96, bp: '110/72', pulse: 102, gcs: 14, respirationRate: 20 },
    registeredTime: '14:20:19',
  },
  {
    id: 'P-632M',
    triageSeverity: 'Critical',
    status: 'In Transit',
    injury: 'Active Arterial Bleed (Femoral)',
    location: 'Vidyavihar Railway Yard Crossing',
    coordinates: [19.0792, 72.8974],
    vitals: { spo2: 90, bp: '88/58', pulse: 126, gcs: 11, respirationRate: 26 },
    assignedAmbulanceId: 'AMB-06',
    assignedHospitalId: 'HOSP-05',
    registeredTime: '14:24:40',
    etaMinutes: 6,
  },
  {
    id: 'P-721Q',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Laceration with Mild Hypothermia',
    location: 'Mahim Bay Coastal Outpost',
    coordinates: [19.0354, 72.8402],
    vitals: { spo2: 99, bp: '118/76', pulse: 72, gcs: 15, respirationRate: 16 },
    registeredTime: '14:05:55',
  },
  {
    id: 'P-844W',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Dislocated Hip & Rib Fractures',
    location: 'Kalanagar Bandra East Junction',
    coordinates: [19.0588, 72.8532],
    vitals: { spo2: 94, bp: '108/70', pulse: 96, gcs: 14, respirationRate: 18 },
    registeredTime: '14:27:12',
  },
  {
    id: 'P-908R',
    triageSeverity: 'Critical',
    status: 'Waiting',
    injury: 'Pediatric Status Epilepticus post-submersion',
    location: 'Mithi River Basin Outflow',
    coordinates: [19.0665, 72.8721],
    vitals: { spo2: 87, bp: '90/60', pulse: 140, gcs: 7, respirationRate: 36 },
    registeredTime: '14:32:01',
  },
  {
    id: 'P-132T',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Sprained Ankle & Dehydration',
    location: 'Sion Circle Relief Tent',
    coordinates: [19.0392, 72.8619],
    vitals: { spo2: 98, bp: '120/80', pulse: 74, gcs: 15, respirationRate: 16 },
    registeredTime: '13:50:20',
  },
  {
    id: 'P-255V',
    triageSeverity: 'Urgent',
    status: 'Allocated',
    injury: 'Crush Injury to Left Forearm',
    location: 'Kurla West Railway Market',
    coordinates: [19.0699, 72.8781],
    vitals: { spo2: 96, bp: '112/74', pulse: 92, gcs: 14, respirationRate: 18 },
    assignedAmbulanceId: 'AMB-19',
    assignedHospitalId: 'HOSP-01',
    registeredTime: '14:21:30',
    etaMinutes: 14,
  },
  {
    id: 'P-377Y',
    triageSeverity: 'Critical',
    status: 'Waiting',
    injury: 'Subarachnoid Hemorrhage & Anisocoria',
    location: 'BKC ICICI Tower Evacuation Zone',
    coordinates: [19.0641, 72.8655],
    vitals: { spo2: 89, bp: '160/100', pulse: 54, gcs: 6, respirationRate: 12 },
    registeredTime: '14:33:10',
  },
  {
    id: 'P-488U',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Fractured Pelvis & Retroperitoneal Bleed',
    location: 'Santacruz Kalina University Gate',
    coordinates: [19.0765, 72.8612],
    vitals: { spo2: 92, bp: '98/62', pulse: 114, gcs: 13, respirationRate: 22 },
    registeredTime: '14:25:50',
  },
  {
    id: 'P-599P',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Multiple Deep Contusions',
    location: 'Dharavi Crossroad Camp',
    coordinates: [19.0478, 72.8541],
    vitals: { spo2: 97, bp: '125/82', pulse: 80, gcs: 15, respirationRate: 16 },
    registeredTime: '14:00:15',
  },
  {
    id: 'P-689L',
    triageSeverity: 'Critical',
    status: 'In Transit',
    injury: 'Pericardial Tamponade (Beck Triad)',
    location: 'LBS Marg Kurla Petrol Depot',
    coordinates: [19.0745, 72.8809],
    vitals: { spo2: 86, bp: '75/50', pulse: 138, gcs: 8, respirationRate: 30 },
    assignedAmbulanceId: 'AMB-01',
    assignedHospitalId: 'HOSP-02',
    registeredTime: '14:23:18',
    etaMinutes: 5,
  },
  {
    id: 'P-770J',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Open Femur Fracture',
    location: 'Chunabhatti Flyover Descent',
    coordinates: [19.0544, 72.8732],
    vitals: { spo2: 95, bp: '106/68', pulse: 100, gcs: 14, respirationRate: 20 },
    registeredTime: '14:19:42',
  },
  {
    id: 'P-862X',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'First Degree Flash Burns',
    location: 'Sion Hospital Outskirts',
    coordinates: [19.0378, 72.8598],
    vitals: { spo2: 99, bp: '119/78', pulse: 75, gcs: 15, respirationRate: 16 },
    registeredTime: '13:48:33',
  },
  {
    id: 'P-955S',
    triageSeverity: 'Critical',
    status: 'Waiting',
    injury: 'Severe Crush Asphyxia & Facial Trauma',
    location: 'M-East Ward Debris Field B',
    coordinates: [19.0581, 72.9125],
    vitals: { spo2: 84, bp: '82/50', pulse: 132, gcs: 7, respirationRate: 32 },
    registeredTime: '14:34:02',
  },
  {
    id: 'P-144D',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Penetrating Thoracoabdominal Shrapnel',
    location: 'Kurla Industrial Estate Gate 4',
    coordinates: [19.0718, 72.8845],
    vitals: { spo2: 93, bp: '102/64', pulse: 108, gcs: 13, respirationRate: 24 },
    registeredTime: '14:27:55',
  },
  {
    id: 'P-266F',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Corneal Abrasion & Dust Inhalation',
    location: 'Bandra Reclamation Tent',
    coordinates: [19.0492, 72.8312],
    vitals: { spo2: 98, bp: '122/80', pulse: 76, gcs: 15, respirationRate: 18 },
    registeredTime: '13:45:10',
  },
  {
    id: 'P-388G',
    triageSeverity: 'Critical',
    status: 'Waiting',
    injury: 'Septic Shock post-sewage submersion',
    location: 'Mithi River Sluice Gate',
    coordinates: [19.0621, 72.8698],
    vitals: { spo2: 88, bp: '76/46', pulse: 145, gcs: 8, respirationRate: 34 },
    registeredTime: '14:35:12',
  },
  {
    id: 'P-499H',
    triageSeverity: 'Urgent',
    status: 'Waiting',
    injury: 'Bilateral Calcaneal Fractures',
    location: 'Tilak Nagar Station Overpass',
    coordinates: [19.0694, 72.8962],
    vitals: { spo2: 96, bp: '114/76', pulse: 94, gcs: 14, respirationRate: 18 },
    registeredTime: '14:16:40',
  },
  {
    id: 'P-610J',
    triageSeverity: 'Delayed',
    status: 'Waiting',
    injury: 'Minor Scalp Laceration',
    location: 'Chembur Swastik Park Staging',
    coordinates: [19.0624, 72.9045],
    vitals: { spo2: 99, bp: '120/78', pulse: 78, gcs: 15, respirationRate: 16 },
    registeredTime: '13:40:00',
  },
];

export const mockAmbulances: Ambulance[] = [
  {
    id: 'AMB-01',
    callsign: 'Apex Fast-Intervention 1',
    type: 'Critical Mobile ICU',
    status: 'En Route',
    leadParamedic: 'Dr. Neha Sen',
    driver: 'Rajesh G.',
    currentLocation: 'Kurla Western Arterial Corridor',
    coordinates: [19.0735, 72.8812],
    fuelPercentage: 88,
    assignedPatientId: 'P-689L',
    destinationHospitalId: 'HOSP-02',
    etaMinutes: 5,
    telemetry: { speedKmh: 58, oxygenLevelPct: 94, batteryPct: 98 },
  },
  {
    id: 'AMB-02',
    callsign: 'Sion Trauma Runner 2',
    type: 'ALS Type II',
    status: 'Transporting',
    leadParamedic: 'Priya K.',
    driver: 'Santosh M.',
    currentLocation: 'Ghatkopar Link Flyover',
    coordinates: [19.0832, 72.9061],
    fuelPercentage: 74,
    assignedPatientId: 'P-404C',
    destinationHospitalId: 'HOSP-02',
    etaMinutes: 9,
    telemetry: { speedKmh: 46, oxygenLevelPct: 88, batteryPct: 92 },
  },
  {
    id: 'AMB-04',
    callsign: 'Lilavati Rapid ALS 4',
    type: 'ALS Type II',
    status: 'Transporting',
    leadParamedic: 'Vikram Joshi (Lead)',
    driver: 'Anil Yadav',
    currentLocation: 'Santacruz-Chembur Bypass',
    coordinates: [19.0715, 72.8795],
    fuelPercentage: 68,
    assignedPatientId: 'P-7F3A',
    destinationHospitalId: 'HOSP-02',
    etaMinutes: 8,
    telemetry: { speedKmh: 52, oxygenLevelPct: 91, batteryPct: 89 },
  },
  {
    id: 'AMB-06',
    callsign: 'KEM Emergency Unit 6',
    type: 'ALS Type I',
    status: 'Transporting',
    leadParamedic: 'Sneha Patel',
    driver: 'Imran Khan',
    currentLocation: 'Vidyavihar Sector 2',
    coordinates: [19.0784, 72.8965],
    fuelPercentage: 82,
    assignedPatientId: 'P-632M',
    destinationHospitalId: 'HOSP-05',
    etaMinutes: 6,
    telemetry: { speedKmh: 61, oxygenLevelPct: 96, batteryPct: 95 },
  },
  {
    id: 'AMB-07',
    callsign: 'Red Cross Mobile 7',
    type: 'BLS',
    status: 'Maintenance',
    leadParamedic: 'Kunal Verma',
    driver: 'Mahesh B.',
    currentLocation: 'Central Depot Maintenance Bay',
    coordinates: [19.052, 72.855],
    fuelPercentage: 35,
    telemetry: { speedKmh: 0, oxygenLevelPct: 40, batteryPct: 60 },
  },
  {
    id: 'AMB-08',
    callsign: 'Sion Municipal ALS 8',
    type: 'ALS Type II',
    status: 'En Route',
    leadParamedic: 'Ritu Nair',
    driver: 'Deepak S.',
    currentLocation: 'Dharavi 90-Feet Road',
    coordinates: [19.0445, 72.858],
    fuelPercentage: 91,
    assignedPatientId: 'P-334F',
    destinationHospitalId: 'HOSP-04',
    etaMinutes: 12,
    telemetry: { speedKmh: 42, oxygenLevelPct: 89, batteryPct: 94 },
  },
  {
    id: 'AMB-10',
    callsign: 'Suburban Aid 10',
    type: 'BLS',
    status: 'Available',
    leadParamedic: 'Arjun Das',
    driver: 'Suresh P.',
    currentLocation: 'Bandra Reclamation Staging Area',
    coordinates: [19.048, 72.833],
    fuelPercentage: 95,
    telemetry: { speedKmh: 0, oxygenLevelPct: 100, batteryPct: 100 },
  },
  {
    id: 'AMB-12',
    callsign: 'Central Trauma Cruiser 12',
    type: 'Critical Mobile ICU',
    status: 'Transporting',
    leadParamedic: 'Dr. Tariq M.',
    driver: 'Sunil Rao',
    currentLocation: 'Sion Circle Approach',
    coordinates: [19.0425, 72.8631],
    fuelPercentage: 79,
    assignedPatientId: 'P-91AC',
    destinationHospitalId: 'HOSP-01',
    etaMinutes: 4,
    telemetry: { speedKmh: 64, oxygenLevelPct: 86, batteryPct: 91 },
  },
  {
    id: 'AMB-14',
    callsign: 'NDRF Special Rescue 14',
    type: 'ALS Type I',
    status: 'Staging',
    leadParamedic: 'Commander S. Rana',
    driver: 'Gopal T.',
    currentLocation: 'Kurla East Sports Complex Staging Hub',
    coordinates: [19.068, 72.885],
    fuelPercentage: 90,
    telemetry: { speedKmh: 0, oxygenLevelPct: 100, batteryPct: 97 },
  },
  {
    id: 'AMB-15',
    callsign: 'Fortis Rapid 15',
    type: 'ALS Type II',
    status: 'Transporting',
    leadParamedic: 'Meera Iyer',
    driver: 'Vijay Solanki',
    currentLocation: 'Tilak Nagar Overpass',
    coordinates: [19.0675, 72.8975],
    fuelPercentage: 84,
    assignedPatientId: 'P-118E',
    destinationHospitalId: 'HOSP-03',
    etaMinutes: 7,
    telemetry: { speedKmh: 55, oxygenLevelPct: 92, batteryPct: 93 },
  },
  {
    id: 'AMB-17',
    callsign: 'Lilavati ALS 17',
    type: 'ALS Type II',
    status: 'Available',
    leadParamedic: 'Ananya Deshmukh',
    driver: 'Pravin Jadhav',
    currentLocation: 'Bandra West Base Station',
    coordinates: [19.055, 72.838],
    fuelPercentage: 96,
    telemetry: { speedKmh: 0, oxygenLevelPct: 98, batteryPct: 99 },
  },
  {
    id: 'AMB-18',
    callsign: 'Municipal Rescue 18',
    type: 'BLS',
    status: 'Available',
    leadParamedic: 'Pankaj More',
    driver: 'Dinesh Shinde',
    currentLocation: 'Chembur Base Camp',
    coordinates: [19.061, 72.902],
    fuelPercentage: 88,
    telemetry: { speedKmh: 0, oxygenLevelPct: 95, batteryPct: 96 },
  },
  {
    id: 'AMB-19',
    callsign: 'Apex Rapid 19',
    type: 'ALS Type I',
    status: 'En Route',
    leadParamedic: 'Sunita Gaikwad',
    driver: 'Harish R.',
    currentLocation: 'LBS Marg Sector 1',
    coordinates: [19.0705, 72.879],
    fuelPercentage: 77,
    assignedPatientId: 'P-255V',
    destinationHospitalId: 'HOSP-01',
    etaMinutes: 14,
    telemetry: { speedKmh: 48, oxygenLevelPct: 90, batteryPct: 90 },
  },
  {
    id: 'AMB-20',
    callsign: 'Seva Trust Mobile 20',
    type: 'BLS',
    status: 'Available',
    leadParamedic: 'Manoj Joshi',
    driver: 'Ganesh K.',
    currentLocation: 'Mahim Causway Point',
    coordinates: [19.038, 72.842],
    fuelPercentage: 92,
    telemetry: { speedKmh: 0, oxygenLevelPct: 98, batteryPct: 98 },
  },
  {
    id: 'AMB-21',
    callsign: 'KEM Annex 21',
    type: 'ALS Type II',
    status: 'Staging',
    leadParamedic: 'Pooja Tiwari',
    driver: 'Ajay K.',
    currentLocation: 'Dharavi Sector 4 Staging',
    coordinates: [19.046, 72.857],
    fuelPercentage: 85,
    telemetry: { speedKmh: 0, oxygenLevelPct: 96, batteryPct: 95 },
  },
  {
    id: 'AMB-22',
    callsign: 'Air Evac Helo 1',
    type: 'Air Evac',
    status: 'Available',
    leadParamedic: 'Capt. Varun Mehta',
    driver: 'Pilot S. Singhania',
    currentLocation: 'Juhu Airbase Helipad',
    coordinates: [19.098, 72.827],
    fuelPercentage: 94,
    telemetry: { speedKmh: 0, oxygenLevelPct: 100, batteryPct: 100 },
  },
  {
    id: 'AMB-23',
    callsign: 'Disaster Rapid 23',
    type: 'Critical Mobile ICU',
    status: 'Available',
    leadParamedic: 'Dr. Amit Shah',
    driver: 'Mohan Lal',
    currentLocation: 'BKC Ground Sector',
    coordinates: [19.066, 72.867],
    fuelPercentage: 90,
    telemetry: { speedKmh: 0, oxygenLevelPct: 97, batteryPct: 99 },
  },
  {
    id: 'AMB-24',
    callsign: 'Suburban Unit 24',
    type: 'BLS',
    status: 'Available',
    leadParamedic: 'Kavita Roy',
    driver: 'Ramesh K.',
    currentLocation: 'Kalina Campus Hub',
    coordinates: [19.075, 72.863],
    fuelPercentage: 89,
    telemetry: { speedKmh: 0, oxygenLevelPct: 94, batteryPct: 94 },
  },
  {
    id: 'AMB-25',
    callsign: 'East Coast Cruiser 25',
    type: 'ALS Type II',
    status: 'Staging',
    leadParamedic: 'Sanjay Rathod',
    driver: 'Akash Sawant',
    currentLocation: 'Ghatkopar Depot',
    coordinates: [19.088, 72.909],
    fuelPercentage: 81,
    telemetry: { speedKmh: 0, oxygenLevelPct: 92, batteryPct: 92 },
  },
];

export const mockHospitals: Hospital[] = [
  {
    id: 'HOSP-01',
    name: 'City Hospital A (Apex Central ED)',
    shortName: 'Apex Central',
    level: 'Facility Level 1 • Trauma Center',
    address: 'Sion West, Mumbai Central Arterial Corridor',
    coordinates: [19.039, 72.862],
    totalIcuBeds: 24,
    availableIcuBeds: 0, // Saturated
    totalGeneralBeds: 180,
    availableGeneralBeds: 14,
    bloodUnits: 42,
    surgeCapability: true,
    contactNumber: '+91-22-2407-6381',
    specialties: ['Cardiothoracic', 'Trauma Bay', 'Mass Burn Unit', 'Neuro ICU'],
  },
  {
    id: 'HOSP-02',
    name: 'City Hospital B (Lilavati Trauma Hub)',
    shortName: 'Lilavati Trauma Hub',
    level: 'Facility Level 1 • Comprehensive ED',
    address: 'Bandra Reclamation, Bandra West',
    coordinates: [19.053, 72.836],
    totalIcuBeds: 30,
    availableIcuBeds: 4,
    totalGeneralBeds: 240,
    availableGeneralBeds: 38,
    bloodUnits: 98,
    surgeCapability: true,
    contactNumber: '+91-22-2675-1000',
    specialties: ['Polytrauma Bay', 'Pediatric ICU', 'Vascular Surgery', 'Blood Bank'],
  },
  {
    id: 'HOSP-03',
    name: 'City Hospital C (KEM Central)',
    shortName: 'KEM Central',
    level: 'Facility Level 1 • Apex Tertiary Hub',
    address: 'Parel, Dr. E Borges Road',
    coordinates: [19.002, 72.843],
    totalIcuBeds: 35,
    availableIcuBeds: 2,
    totalGeneralBeds: 320,
    availableGeneralBeds: 22,
    bloodUnits: 115,
    surgeCapability: true,
    contactNumber: '+91-22-2410-7000',
    specialties: ['Neurosurgery', 'Organ Transplant', 'Trauma Resuscitation', 'Toxicology'],
  },
  {
    id: 'HOSP-04',
    name: 'Sion Municipal Trauma Center',
    shortName: 'Sion Municipal',
    level: 'Facility Level 2 • Emergency Resuscitation',
    address: 'Sion Circle, Eastern Express Highway',
    coordinates: [19.038, 72.861],
    totalIcuBeds: 20,
    availableIcuBeds: 1,
    totalGeneralBeds: 190,
    availableGeneralBeds: 9,
    bloodUnits: 36,
    surgeCapability: false,
    contactNumber: '+91-22-2407-6384',
    specialties: ['Crash Bay', 'Orthopedics', 'Invasive Ventilation'],
  },
  {
    id: 'HOSP-05',
    name: 'Suburban General & Emergency',
    shortName: 'Suburban General',
    level: 'Facility Level 2 • Acute Care',
    address: 'Vidyavihar East, Station Road',
    coordinates: [19.081, 72.899],
    totalIcuBeds: 16,
    availableIcuBeds: 0,
    totalGeneralBeds: 140,
    availableGeneralBeds: 6,
    bloodUnits: 18,
    surgeCapability: false,
    contactNumber: '+91-22-2512-4400',
    specialties: ['Internal Medicine', 'Basic Trauma', 'Observation Bay'],
  },
  {
    id: 'HOSP-06',
    name: 'Fortis Disaster Annex',
    shortName: 'Fortis Annex',
    level: 'Facility Level 1 • Emergency Annex',
    address: 'Mulund-Bhandup Link Rd',
    coordinates: [19.155, 72.941],
    totalIcuBeds: 28,
    availableIcuBeds: 6,
    totalGeneralBeds: 210,
    availableGeneralBeds: 45,
    bloodUnits: 82,
    surgeCapability: true,
    contactNumber: '+91-22-4365-4365',
    specialties: ['Cardiac Care', 'Advanced ICU', 'Pediatric Emergency'],
  },
];

export const mockBloodInventory: BloodInventory[] = [
  {
    type: 'O-',
    unitsAvailable: 8,
    unitsReserved: 6,
    criticalThreshold: 20,
    status: 'Critical',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 4 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 3 },
      { hospitalId: 'HOSP-01', hospitalName: 'Apex Central', units: 1 },
    ],
  },
  {
    type: 'O+',
    unitsAvailable: 64,
    unitsReserved: 30,
    criticalThreshold: 40,
    status: 'Adequate',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 28 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 22 },
      { hospitalId: 'HOSP-06', hospitalName: 'Fortis Annex', units: 14 },
    ],
  },
  {
    type: 'A-',
    unitsAvailable: 14,
    unitsReserved: 8,
    criticalThreshold: 15,
    status: 'Low',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 7 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 5 },
      { hospitalId: 'HOSP-01', hospitalName: 'Apex Central', units: 2 },
    ],
  },
  {
    type: 'A+',
    unitsAvailable: 88,
    unitsReserved: 24,
    criticalThreshold: 35,
    status: 'Surplus',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 36 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 32 },
      { hospitalId: 'HOSP-06', hospitalName: 'Fortis Annex', units: 20 },
    ],
  },
  {
    type: 'B-',
    unitsAvailable: 12,
    unitsReserved: 6,
    criticalThreshold: 15,
    status: 'Low',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 6 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 4 },
      { hospitalId: 'HOSP-04', hospitalName: 'Sion Municipal', units: 2 },
    ],
  },
  {
    type: 'B+',
    unitsAvailable: 76,
    unitsReserved: 20,
    criticalThreshold: 35,
    status: 'Surplus',
    hospitalDistribution: [
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 34 },
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 24 },
      { hospitalId: 'HOSP-06', hospitalName: 'Fortis Annex', units: 18 },
    ],
  },
  {
    type: 'AB-',
    unitsAvailable: 6,
    unitsReserved: 4,
    criticalThreshold: 10,
    status: 'Critical',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 3 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 3 },
    ],
  },
  {
    type: 'AB+',
    unitsAvailable: 32,
    unitsReserved: 10,
    criticalThreshold: 20,
    status: 'Adequate',
    hospitalDistribution: [
      { hospitalId: 'HOSP-02', hospitalName: 'Lilavati Trauma Hub', units: 14 },
      { hospitalId: 'HOSP-03', hospitalName: 'KEM Central', units: 12 },
      { hospitalId: 'HOSP-06', hospitalName: 'Fortis Annex', units: 6 },
    ],
  },
];

export const mockMedicines: Medicine[] = [
  {
    id: 'MED-101',
    name: 'Tranexamic Acid (TXA 1000mg/10ml)',
    category: 'Trauma Care',
    stockCount: 142,
    unit: 'Vials',
    minimumRequired: 200,
    expiryDate: '2027-08-15',
    urgency: 'Low',
  },
  {
    id: 'MED-102',
    name: 'Propofol 1% Injectable Emulsion',
    category: 'Anesthetic',
    stockCount: 56,
    unit: 'Amps',
    minimumRequired: 80,
    expiryDate: '2026-11-20',
    urgency: 'Low',
  },
  {
    id: 'MED-103',
    name: 'Ceftriaxone 2g IV Antibiotic',
    category: 'Antibiotic',
    stockCount: 380,
    unit: 'Vials',
    minimumRequired: 250,
    expiryDate: '2028-01-10',
    urgency: 'Sufficient',
  },
  {
    id: 'MED-104',
    name: 'Epinephrine 1:1000 Auto-Inject/Amps',
    category: 'Cardiovascular',
    stockCount: 220,
    unit: 'Amps',
    minimumRequired: 150,
    expiryDate: '2027-05-30',
    urgency: 'Sufficient',
  },
  {
    id: 'MED-105',
    name: 'Succinylcholine 100mg/5ml RSI Kit',
    category: 'Respiratory',
    stockCount: 18,
    unit: 'Kits',
    minimumRequired: 50,
    expiryDate: '2026-12-05',
    urgency: 'Deficit',
  },
  {
    id: 'MED-106',
    name: 'Whole Blood Cryoprecipitate',
    category: 'Trauma Care',
    stockCount: 24,
    unit: 'Units',
    minimumRequired: 60,
    expiryDate: '2026-10-25',
    urgency: 'Deficit',
  },
];

export const mockDecisionExplanation: Record<string, any> = {
  'P-7F3A': {
    patientId: 'P-7F3A',
    patientSeverity: 'Critical (Tier 1 Trauma)',
    ambulanceId: 'AMB-04',
    ambulanceType: 'ALS Type II • Paramedic Lead',
    hospitalId: 'HOSP-02',
    hospitalName: 'Lilavati Trauma Center',
    globalScore: 93.6,
    etaMinutes: 8,
    optimalTransitText: 'Optimal Transit: 8.2m | +0m detour',
    factors: [
      {
        name: 'Patient Urgency',
        score: 100,
        weight: '35%',
        color: '#DC2626',
        reason: 'Immediate invasive ventilation indicated by on-scene telemetry (SpO2: 88%)',
      },
      {
        name: 'Ambulance Capability Match',
        score: 100,
        weight: '25%',
        color: '#155EEF',
        reason: 'ALS Unit 04 equipped with mechanical ventilator & RSI airway kit',
      },
      {
        name: 'Transit & Route Efficiency',
        score: 85,
        weight: '20%',
        color: '#0EA5E9',
        reason: '8 mins travel time; avoided inundated Santacruz-Chembur bottleneck',
      },
      {
        name: 'Hospital Capacity & Equipment Fit',
        score: 88,
        weight: '20%',
        color: '#16A34A',
        reason: 'Lilavati has 4 verified ICU beds & matching blood inventory (O- reserve: 4 units)',
      },
    ],
    alternativesConsidered: [
      {
        hospitalName: 'City Hospital A (Apex Central ED)',
        score: 52.4,
        deltaMinutes: -2,
        rejectionReason: 'ICU Saturated (0/24 beds). Diverting patient avoids lethal triage wait.',
      },
      {
        hospitalName: 'Sion Municipal Trauma Center',
        score: 71.0,
        deltaMinutes: +5,
        rejectionReason: 'Bridge B12 hazard blocks direct corridor; +14 min flood detour required.',
      },
      {
        hospitalName: 'KEM Central Apex',
        score: 64.8,
        deltaMinutes: +12,
        rejectionReason: 'Sub-optimal travel latency (20m total); exceeds Tier-1 Golden Hour window.',
      },
    ],
    mathematicalProof: {
      solverType: 'Deterministic Multi-Commodity Simplex (MILP v4.2)',
      iterations: 1428,
      optimalityGap: '0.00% (Strictly Global Optimum)',
      shadowPrice: 'λ_bed = 4.82 | λ_transit = -1.15',
    },
  },
};

export const mockAllocations: Allocation[] = [
  {
    id: 'ALC-884-01',
    timestamp: '14:28:15',
    patientId: 'P-7F3A',
    severity: 'Critical',
    ambulanceId: 'AMB-04',
    hospitalId: 'HOSP-02',
    hospitalName: 'Lilavati Trauma Center',
    score: 93.6,
    etaMinutes: 8,
    status: 'En Route',
    decisionExplanation: mockDecisionExplanation['P-7F3A'],
  },
  {
    id: 'ALC-884-02',
    timestamp: '14:22:20',
    patientId: 'P-91AC',
    severity: 'Critical',
    ambulanceId: 'AMB-12',
    hospitalId: 'HOSP-01',
    hospitalName: 'Apex Central ED',
    score: 91.2,
    etaMinutes: 4,
    status: 'En Route',
    decisionExplanation: {
      ...mockDecisionExplanation['P-7F3A'],
      patientId: 'P-91AC',
      patientSeverity: 'Critical (Crush Syndrome)',
      ambulanceId: 'AMB-12',
      hospitalName: 'Apex Central ED',
      globalScore: 91.2,
      etaMinutes: 4,
    },
  },
  {
    id: 'ALC-884-03',
    timestamp: '14:24:45',
    patientId: 'P-632M',
    severity: 'Critical',
    ambulanceId: 'AMB-06',
    hospitalId: 'HOSP-05',
    hospitalName: 'Suburban General',
    score: 87.5,
    etaMinutes: 6,
    status: 'En Route',
    decisionExplanation: {
      ...mockDecisionExplanation['P-7F3A'],
      patientId: 'P-632M',
      patientSeverity: 'Critical (Arterial Bleed)',
      ambulanceId: 'AMB-06',
      hospitalName: 'Suburban General',
      globalScore: 87.5,
      etaMinutes: 6,
    },
  },
  {
    id: 'ALC-884-04',
    timestamp: '14:23:25',
    patientId: 'P-689L',
    severity: 'Critical',
    ambulanceId: 'AMB-01',
    hospitalId: 'HOSP-02',
    hospitalName: 'Lilavati Trauma Center',
    score: 94.8,
    etaMinutes: 5,
    status: 'En Route',
    decisionExplanation: {
      ...mockDecisionExplanation['P-7F3A'],
      patientId: 'P-689L',
      patientSeverity: 'Critical (Cardiac Tamponade)',
      ambulanceId: 'AMB-01',
      hospitalName: 'Lilavati Trauma Center',
      globalScore: 94.8,
      etaMinutes: 5,
    },
  },
  {
    id: 'ALC-884-05',
    timestamp: '14:18:10',
    patientId: 'P-334F',
    severity: 'Urgent',
    ambulanceId: 'AMB-08',
    hospitalId: 'HOSP-04',
    hospitalName: 'Sion Municipal',
    score: 82.1,
    etaMinutes: 12,
    status: 'Dispatched',
    decisionExplanation: {
      ...mockDecisionExplanation['P-7F3A'],
      patientId: 'P-334F',
      patientSeverity: 'Urgent (Blast Concussion)',
      ambulanceId: 'AMB-08',
      hospitalName: 'Sion Municipal',
      globalScore: 82.1,
      etaMinutes: 12,
    },
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-101',
    title: 'Hospital A (Apex Central) ICU Full',
    description: 'Capacity saturated at 24/24 beds. Automated routing diversion activated for inbound Tier-1 patients.',
    severity: 'critical',
    category: 'Medical Capacity',
    timestamp: '14:30:12',
    timeAgo: '2m ago',
    acknowledged: false,
    actionLabel: 'View Diversion Map',
    actionTarget: '/live',
  },
  {
    id: 'ALT-102',
    title: 'O- Blood Low Across Zone',
    description: 'Reserve at 8 units (Threshold: 20 units). Urgent replenishment requisition dispatched to Red Cross Blood Bank.',
    severity: 'critical',
    category: 'Medical Capacity',
    timestamp: '14:26:40',
    timeAgo: '6m ago',
    acknowledged: false,
    actionLabel: 'Open Blood Grid',
    actionTarget: '/resources',
  },
  {
    id: 'ALT-103',
    title: 'Bridge B12 Blocked (Flash Flood Cut-off)',
    description: 'Santacruz-Chembur link artery inundated with 1.4m standing water. Tactical rerouting active for 4 field units.',
    severity: 'critical',
    category: 'Infrastructure',
    timestamp: '14:15:00',
    timeAgo: '17m ago',
    acknowledged: false,
    actionLabel: 'Inspect Tactical Route',
    actionTarget: '/live',
  },
  {
    id: 'ALT-104',
    title: 'Ambulance A-17 Arrived Lilavati ED',
    description: 'Patient P-7F3A transfer into Trauma Bay 04 initiated. Unit turnaround cycle running (14m estimated).',
    severity: 'info',
    category: 'Fleet',
    timestamp: '14:32:00',
    timeAgo: 'Just now',
    acknowledged: true,
  },
  {
    id: 'ALT-105',
    title: 'Casualty Surge Wave Detected in Sector 4',
    description: 'Harbor Link industrial perimeter reported structural collapse. Estimated +25 casualties inbound.',
    severity: 'warning',
    category: 'Triage Queue',
    timestamp: '14:12:00',
    timeAgo: '20m ago',
    acknowledged: false,
    actionLabel: 'Review Queue',
    actionTarget: '/patients',
  },
];

export const mockLedgerBlocks: LedgerBlock[] = [
  {
    blockNumber: 1284,
    hash: '0x8f2c3a9d71b4e5a82c0f6419e782d3ca45b17e8890dfac01',
    prevHash: '0x4e7b89a01c34f2d56a7891bcdef0123456789abcdeff0123',
    timestamp: '14:32:08 UTC',
    actionType: 'Patient Dispatch',
    entity: 'RESQ Multi-Commodity Simplex Solver',
    transactionCount: 4,
    validator: 'Maharashtra State Disaster Management Authority (SDMA)',
    signature: 'ed25519:3b9f4a1...9a7e2c',
    verified: true,
    payloadSummary: 'Dispatch P-7F3A -> AMB-04 -> Lilavati Trauma Hub. Constraint: Golden Hour ETA < 15m.',
    details: {
      sender: 'RESQ Autonomous Dispatch Kernel v4.2',
      recipient: 'Lilavati Trauma Hub (Bay 04)',
      amountOrAsset: 'Patient P-7F3A (Tier 1 Trauma Evacuation)',
      auditProof: 'SHA256: 0x8f2c...ac01 (Verified Ed25519 Multi-Sig)',
      timestampUtc: '2026-10-03T14:32:08Z',
    },
  },
  {
    blockNumber: 1283,
    hash: '0x4e7b89a01c34f2d56a7891bcdef0123456789abcdeff0123',
    prevHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f',
    timestamp: '14:25:00 UTC',
    actionType: 'Fund Disbursement',
    entity: 'SDMA Relief Cell Treasury',
    transactionCount: 2,
    validator: 'Comptroller & Public Auditor General',
    signature: 'ed25519:7c2b1a9...4d5e6f',
    verified: true,
    payloadSummary: 'Disbursement of ₹1,80,00,000 to Red Cross & Seva Mobile Response Teams.',
    details: {
      sender: 'SDMA Disaster Relief Escrow Pool',
      recipient: 'Red Cross & Seva Emergency Mission',
      amountOrAsset: '₹1,80,00,000 INR (Emergency Aid Tranche 2)',
      auditProof: 'SHA256: 0x4e7b...0123 (Verified Multi-Sig Treasury)',
      timestampUtc: '2026-10-03T14:25:00Z',
    },
  },
  {
    blockNumber: 1282,
    hash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f',
    prevHash: '0x99aa88bb77cc66dd55ee44ff33221100aabbccddeeff0011',
    timestamp: '14:15:10 UTC',
    actionType: 'Medical Restock',
    entity: 'Central Medical Supplies Depot',
    transactionCount: 6,
    validator: 'Indian Red Cross Society',
    signature: 'ed25519:1d4f8e2...3a5c7b',
    verified: true,
    payloadSummary: 'Allocation of 120 units O+ blood & 200 TXA vials to Lilavati Trauma Center.',
    details: {
      sender: 'Central Blood Bank & Surgical Depot',
      recipient: 'Lilavati Trauma Hub Pharmacy',
      amountOrAsset: '120 Blood Units + 200 TXA Vials',
      auditProof: 'SHA256: 0x1a2b...3e4f (Verified Supply Chain)',
      timestampUtc: '2026-10-03T14:15:10Z',
    },
  },
  {
    blockNumber: 1281,
    hash: '0x99aa88bb77cc66dd55ee44ff33221100aabbccddeeff0011',
    prevHash: '0x556677889900aabbccddeeff112233445566778899aabbcc',
    timestamp: '14:00:00 UTC',
    actionType: 'ICU Reallocation',
    entity: 'Disaster Health Command',
    transactionCount: 3,
    validator: 'Brihanmumbai Municipal Corporation (BMC)',
    signature: 'ed25519:88aa22c...11ee44',
    verified: true,
    payloadSummary: 'Emergency surge authorization: 12 additional surge beds activated at Fortis Annex.',
    details: {
      sender: 'BMC Public Health Department',
      recipient: 'Fortis Disaster Annex',
      amountOrAsset: '12 Surge Trauma Beds Reallocated',
      auditProof: 'SHA256: 0x99aa...0011 (Verified Executive Order)',
      timestampUtc: '2026-10-03T14:00:00Z',
    },
  },
];

export const mockFundTransfers: FundTransfer[] = [
  {
    id: 'FND-01',
    stageName: 'Donor / Treasury',
    organization: 'International Disaster Relief Trust (IDRT) / Corporate CSR Pool',
    role: 'Originating Capital Anchor',
    allocatedAmountInr: 100000000, // ₹10.00 Cr
    utilizedAmountInr: 85000000,
    balanceAmountInr: 15000000,
    percentageDeployed: 85,
    status: 'Verified & Audited',
    lastTxHash: '0x3f4a9b2c8e1d70a9',
    beneficiariesCount: 18400,
    timestamp: '06:00:00 UTC',
  },
  {
    id: 'FND-02',
    stageName: 'Government Hub',
    organization: 'State Disaster Management Authority (SDMA Relief Cell)',
    role: 'State Oversight & Statutory Escrow',
    allocatedAmountInr: 85000000, // ₹8.50 Cr
    utilizedAmountInr: 68000000,
    balanceAmountInr: 17000000,
    percentageDeployed: 80,
    status: 'Verified & Audited',
    lastTxHash: '0x7b1c4e9f2a806d3e',
    beneficiariesCount: 14200,
    timestamp: '08:30:00 UTC',
  },
  {
    id: 'FND-03',
    stageName: 'NGO Partner',
    organization: 'Red Cross & Seva Emergency Relief Mission',
    role: 'Logistics Deployment & Medical Field Distribution',
    allocatedAmountInr: 68000000, // ₹6.80 Cr
    utilizedAmountInr: 54000000,
    balanceAmountInr: 14000000,
    percentageDeployed: 79,
    status: 'Verified & Audited',
    lastTxHash: '0x9d2a6c4f1e07b8a5',
    beneficiariesCount: 9800,
    timestamp: '11:15:00 UTC',
  },
  {
    id: 'FND-04',
    stageName: 'Field Worker / Base',
    organization: 'Mobile Response Team Lead (Worker: Priya K. — Unit 04)',
    role: 'Direct Material & Emergency Voucher Distribution',
    allocatedAmountInr: 54000000, // ₹5.40 Cr
    utilizedAmountInr: 49500000,
    balanceAmountInr: 4500000,
    percentageDeployed: 92,
    status: 'Verified & Audited',
    lastTxHash: '0x4a8c1e7f9b02d6a3',
    beneficiariesCount: 6400,
    timestamp: '13:00:00 UTC',
  },
  {
    id: 'FND-05',
    stageName: 'Beneficiary Aid',
    organization: 'Displaced Resident Families (Cohort #8402 / Sector 4 Camp)',
    role: 'Verified Direct Beneficiary Wallets & Physical Aid Kits',
    allocatedAmountInr: 49500000, // ₹4.95 Cr
    utilizedAmountInr: 49500000,
    balanceAmountInr: 0,
    percentageDeployed: 100,
    status: 'Verified & Audited',
    lastTxHash: '0x8f2c3a9d71b4e5a8',
    beneficiariesCount: 5200,
    timestamp: '14:20:00 UTC',
  },
];

export const mockSimulationTimeline: SimulationEvent[] = [
  {
    id: 'EVT-01',
    timestamp: '14:32:08',
    title: 'Disaster Operations Active Cycle #884',
    description: 'Deterministic MILP Optimizer synchronized 38 triage priorities across 5 active receiving hubs.',
    severity: 'info',
  },
  {
    id: 'EVT-02',
    timestamp: '14:15:00',
    title: 'Bridge B12 Structural Disruption Simulated',
    description: 'Santacruz-Chembur link artery inundated. 4 ambulance trajectories rerouted around arterial cut-off.',
    severity: 'critical',
  },
  {
    id: 'EVT-03',
    timestamp: '14:02:18',
    title: 'Apex Central ICU Saturated',
    description: 'Available critical care beds dropped to 0. Dynamic diversion avoidance active.',
    severity: 'warning',
  },
  {
    id: 'EVT-04',
    timestamp: '13:45:00',
    title: 'Monsoon Flash Flood Surge Initiated',
    description: 'Baseline parameters set: 50 patients in queue, 25 fleet active, 300 blood reserve units.',
    severity: 'info',
  },
];
