/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "on-tertiary": "#ffffff",
        "secondary": "#006591",
        "on-tertiary-container": "#ffe5e2",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#d01c1f",
        "secondary-fixed": "#c9e6ff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed-variant": "#004c6e",
        "on-primary-fixed": "#00174b",
        "surface-container-high": "#e1e8ff",
        "surface-container": "#e9edff",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d8",
        "on-primary-container": "#e7eaff",
        "on-tertiary-fixed": "#410002",
        "secondary-fixed-dim": "#89ceff",
        "on-secondary-fixed": "#001e2f",
        "primary": "#0047c1",
        "on-background": "#121b2e",
        "outline": "#737687",
        "on-tertiary-fixed-variant": "#93000b",
        "tertiary-fixed": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "on-secondary-container": "#004666",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#003da9",
        "surface": "#f9f9ff",
        "surface-variant": "#d9e2fc",
        "surface-container-highest": "#d9e2fc",
        "primary-container": "#155eef",
        "on-surface": "#121b2e",
        "tertiary-fixed-dim": "#ffb4ab",
        "inverse-surface": "#273044",
        "inverse-on-surface": "#edf0ff",
        "inverse-primary": "#b4c5ff",
        "surface-container-low": "#f1f3ff",
        "background": "#f9f9ff",
        "surface-tint": "#0052dc",
        "tertiary": "#a8000f",
        "primary-fixed": "#dbe1ff",
        "error": "#ba1a1a",
        "surface-dim": "#d1daf4",
        "secondary-container": "#39b8fd"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "gutter": "1rem",
        "space-md": "0.75rem",
        "gutter-desktop": "1.25rem",
        "space-sm": "0.5rem",
        "margin-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
        "space-lg": "1.25rem"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-sm": ["Inter", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
}
